version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: scaperoom-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: scape_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
